server:
  port: 8080
  servlet:
    context-path: /utils

#spring:
#  application:
#    name: bill-admin
#  http:
#    encoding: utf-8
#  datasource:
#    url: jdbc:mysql://localhost:3306/bill_admin?characterEncoding=utf-8&serverTimezone=GMT%2B8
#    username: root
#    password: root
#    driverClassName: com.mysql.cj.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848

#mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml
#  typeAliasesPackage: com.wmhou.admin.entity
#  global-config:
#    db-config:
#      id-type: ID-WORKER
#      field-strategy: NOT_NULL
#      column-underline: true
#    banner: false



logging:
  level:
    com.wmhou.admin.mapper: DEBUG
